# Generated by Django 3.2.7 on 2022-06-24 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cat_img', models.ImageField(default='images/floric.jpg', upload_to='images/category/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('description', models.CharField(max_length=5119)),
                ('weight', models.CharField(blank=True, max_length=1023, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField()),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_img1', models.ImageField(default='images/floric.jpg', upload_to='images/products/')),
                ('product_img2', models.ImageField(blank=True, default='images/floric.jpg', null=True, upload_to='images/products/')),
                ('product_img3', models.ImageField(blank=True, default='images/floric.jpg', null=True, upload_to='images/products/')),
                ('product_img4', models.ImageField(blank=True, default='images/floric.jpg', null=True, upload_to='images/products/')),
            ],
        ),
    ]
