# Generated by Django 3.2.7 on 2022-07-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_user_order_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_img',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
