# Generated by Django 3.2.7 on 2022-07-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20220703_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=15, null=True),
        ),
    ]
