# Generated by Django 3.2.7 on 2022-07-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='Processing', max_length=15, null=True),
        ),
    ]
