# Generated by Django 3.2.7 on 2022-06-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product_img', models.ImageField(default='images/floric.jpg', upload_to='images/carts/')),
                ('product_name', models.CharField(default='item', max_length=512)),
                ('product_price', models.FloatField(default=0.0)),
            ],
        ),
    ]
